#!/usr/bin/env python3
"""
build_index.py  –  Scan profiles/ subdirectories, read metadata.json files,
and emit a self-contained profiles/index.html GitHub Pages listing.

Usage:
    python3 build_index.py [profiles_dir]
    python3 build_index.py                   # defaults to ./profiles/
"""

import json, sys, os
from pathlib import Path
from datetime import datetime

INDEX_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>GPU Perf Profiles</title>
<style>
*{box-sizing:border-box;margin:0;padding:0;font-family:'Segoe UI',system-ui,sans-serif}
body{background:#1a1a2e;color:#e0e0e0;padding:20px 28px}
h1{font-size:20px;color:#a8dadc;margin-bottom:4px}
.sub{font-size:12px;color:#666;margin-bottom:20px}
table{width:100%;border-collapse:collapse;font-size:12px}
th{background:#16213e;color:#a8dadc;padding:7px 10px;text-align:left;
   border-bottom:2px solid #0f3460;white-space:nowrap}
td{padding:6px 10px;border-bottom:1px solid rgba(255,255,255,0.05);vertical-align:top}
tr:hover td{background:rgba(168,218,220,0.05)}
.mono{font-family:monospace;font-size:11px}
.commit{color:#e67e22}
.branch{color:#a8dadc}
.gpu{color:#9b59b6;font-size:10px}
.links a{display:inline-block;margin:1px 3px 1px 0;padding:3px 7px;border-radius:3px;
         background:#0f3460;color:#a8dadc;text-decoration:none;font-size:10px;
         border:1px solid rgba(168,218,220,0.2)}
.links a:hover{background:#1a4a7a;color:#e0e0e0}
.notes{font-size:10px;color:#888;margin-top:3px}
.date{color:#bbb;white-space:nowrap}
</style>
</head>
<body>
<h1>GPU Perf Profiles</h1>
<div class="sub">Auto-generated by build_index.py — {n} profile sets</div>
<table>
<thead><tr>
  <th>Date</th><th>Label / SF</th><th>Branch · Commit</th>
  <th>Machine · GPU</th><th>Files</th><th>Notes</th>
</tr></thead>
<tbody>
{rows}
</tbody>
</table>
<div style="margin-top:16px;font-size:10px;color:#444">
  Large .nsys-rep files are attached to GitHub Releases — not committed to this repo.
  HTML timelines are self-contained and open in any browser.
</div>
</body>
</html>
"""

ROW = """\
<tr>
  <td class="date mono">{date}</td>
  <td class="mono"><b>{label}</b><br>SF={sf}</td>
  <td class="mono"><span class="branch">{branch}</span><br><span class="commit">{commit}</span><br><span style="font-size:9px;color:#666">{commit_msg}</span></td>
  <td class="gpu">{machine}<br>{gpu}</td>
  <td class="links">{links}</td>
  <td><div class="notes">{notes}</div></td>
</tr>"""


def scan_profiles(profiles_dir: Path):
    entries = []
    for sub in sorted(profiles_dir.iterdir(), reverse=True):
        if not sub.is_dir():
            continue
        meta_path = sub / "metadata.json"
        if not meta_path.exists():
            # Legacy flat HTML files — skip directories without metadata
            continue
        try:
            meta = json.loads(meta_path.read_text())
        except Exception as e:
            print(f"  WARN: bad metadata in {sub}: {e}")
            continue
        entries.append((sub, meta))
    return entries


def make_links(sub: Path, meta: dict) -> str:
    files = meta.get("files", {})
    links = []
    for key, fname in files.items():
        if fname == "null" or not fname:
            continue
        fpath = sub / fname
        if not fpath.exists():
            continue
        size_kb = fpath.stat().st_size // 1024
        size_str = f"{size_kb}KB" if size_kb < 1024 else f"{size_kb//1024}MB"
        label_map = {
            "html_gpu":      f"GPU timeline ({size_str})",
            "html_combined": f"GPU+CPU timeline ({size_str})",
            "sqlite":        f"SQLite ({size_str})",
            "nsys_rep":      f".nsys-rep ({size_str})",
            "cpu_json":      f"CPU JSON ({size_str})",
        }
        label = label_map.get(key, f"{key} ({size_str})")
        rel   = fname  # relative to the profiles/ dir
        links.append(f'<a href="{sub.name}/{fname}">{label}</a>')

    # Also scan for any .html files not listed in meta
    for html in sorted(sub.glob("*.html")):
        fname = html.name
        if any(fname in v for v in files.values()):
            continue
        size_kb = html.stat().st_size // 1024
        links.append(f'<a href="{sub.name}/{fname}">{fname} ({size_kb}KB)</a>')

    return "\n".join(links) if links else "(no HTML yet)"


def main():
    profiles_dir = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("profiles")
    if not profiles_dir.exists():
        print(f"ERROR: {profiles_dir} not found"); sys.exit(1)

    print(f"Scanning {profiles_dir} …")
    entries = scan_profiles(profiles_dir)
    print(f"  {len(entries)} profile sets found")

    rows = []
    for sub, meta in entries:
        links = make_links(sub, meta)
        row = ROW.format(
            date        = meta.get("date", "?"),
            label       = meta.get("label", sub.name),
            sf          = meta.get("scale_factor", "?"),
            branch      = meta.get("branch", "?"),
            commit      = meta.get("commit", "?"),
            commit_msg  = (meta.get("commit_message", "") or "")[:60],
            machine     = meta.get("machine", "?"),
            gpu         = meta.get("gpu", "?"),
            links       = links,
            notes       = meta.get("notes", ""),
        )
        rows.append(row)

    out_path = profiles_dir / "index.html"
    html = (INDEX_HTML
            .replace("{n}",    str(len(entries)))
            .replace("{rows}", "\n".join(rows)))
    out_path.write_text(html, encoding="utf-8")
    print(f"Written: {out_path}  ({out_path.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
